# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe4cb44201369a733635d83549035038605dfd294a0fa6ea74ddd23eeea2702675ac7056834192837773e7953ab9563dc86c5e0dedbef867ec736148760569f4

test:
  secret_key_base: 434d4ada36faa408d32393e3a9588321795a273a87b4fefaa55503f029c7169c03305b2717b040b3a6f050363368e632f345483f6c96e09020a39d02e6cb57ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
